<a href="https://colab.research.google.com/github/Alifiamutiaaa/UASMachineLearning/blob/main/UASML_TensorBasic_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Basic
---


In [ ]:
import torch

In [ ]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([5.0202e-35])


In [ ]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([4.3813e+15, 4.5827e-41, 5.4754e-35])


In [ ]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[5.4887e-35, 0.0000e+00, 5.0091e-35],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])


In [ ]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)

tensor([[[4.3813e+15, 4.5827e-41, 4.3813e+15],
         [4.5827e-41, 4.4842e-44, 0.0000e+00]],

        [[1.5695e-43, 0.0000e+00, 5.0385e-35],
         [0.0000e+00, 1.7937e-43, 0.0000e+00]]])


In [ ]:
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[[4.3813e+15, 4.5827e-41, 4.9547e-35],
          [0.0000e+00, 4.4842e-44, 0.0000e+00]],

         [[8.9683e-44, 0.0000e+00, 5.4808e-35],
          [0.0000e+00, 4.3813e+15, 4.5827e-41]]],


        [[[2.1715e-18, 2.3081e-12, 1.8590e+34],
          [7.7767e+31, 1.7181e+19, 1.8990e+28]],

         [[2.0319e-43, 0.0000e+00, 5.0366e-35],
          [0.0000e+00, 1.8077e-43, 0.0000e+00]]]])


In [ ]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.9159, 0.1829, 0.1446],
        [0.0969, 0.0464, 0.9672],
        [0.6482, 0.1569, 0.1383],
        [0.9866, 0.9603, 0.8960],
        [0.6557, 0.1100, 0.5303]])


In [ ]:
# check size
print(x.size())

torch.Size([5, 3])


In [ ]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# specify types, int default
x = torch.ones(2,2, dtype=torch.int)
print(x.dtype)

torch.int32


In [ ]:
x = torch.ones(2,2, dtype=torch.double)
print(x.dtype)

torch.float64


In [ ]:
# construct from data
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
# operations
x = torch.rand(2,2)
y = torch.rand(2,2)

In [ ]:
# substraction
z = x - y
z = torch.sub(x,y)
print(z)

tensor([[-0.5215,  0.0591],
        [ 0.5480,  0.2572]])


In [ ]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.3068, 0.9836, 0.6979],
        [0.6225, 0.3315, 0.3341],
        [0.3287, 0.4280, 0.8333],
        [0.9463, 0.0881, 0.2109],
        [0.6394, 0.7487, 0.4732]])
tensor([0.3068, 0.6225, 0.3287, 0.9463, 0.6394])
tensor([0.6225, 0.3315, 0.3341])
tensor(0.3315)


In [ ]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.33154720067977905


In [ ]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
