<a href="https://colab.research.google.com/github/Alifiamutiaaa/UASMachineLearning/blob/main/UASML_AutoGrad_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Autograd
---

In [30]:
import torch

In [31]:
x = torch.randn(3)
print(x)

tensor([0.0074, 0.9593, 0.8148])


In [32]:
# track all operations on the tensor
x = torch.randn(3, requires_grad=True)
y = x + 2

print(x)
print(y)
print(y.grad_fn)

tensor([-0.0474, -0.7538,  0.1812], requires_grad=True)
tensor([1.9526, 1.2462, 2.1812], grad_fn=<AddBackward0>)


In [33]:
# operations on y
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([11.4384,  4.6592, 14.2734], grad_fn=<MulBackward0>)
tensor(10.1236, grad_fn=<MeanBackward0>)


In [34]:
z.backward()
print(x.grad) # dz/dx

tensor([3.9053, 2.4924, 4.3625])


In [35]:
x = torch.randn(3, requires_grad=True)

y = x * 2
for _ in range(10):
  y = y * 2

print(y)
print(y.shape)

tensor([-1605.6176, -3647.4531, -1329.6210], grad_fn=<MulBackward0>)
torch.Size([3])


In [36]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float32)
y.backward(v)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [37]:
# .requires_grad_(...) changes an existing flag in-place.
a = torch.randn(2, 2)
print(a.requires_grad)
b = ((a * 3) / (a - 1))
print(b.grad_fn)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
None
True


In [38]:
# .detach(): get a new Tensor with the same content but no gradient computation:
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
b = a.detach()
print(b.requires_grad)

True
False


In [39]:
# wrap in 'with torch.no_grad():'
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
False


In [40]:
# Use .zero_() to empty the gradients before a new optimization step!
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    # just a dummy example
    model_output = (weights*3).sum()
    model_output.backward()

    print(weights.grad)

    # optimize model
    with torch.no_grad():
      weights -= 0.1 * weights.grad

    weights.grad.zero_()

print(weights)
print(model_output)

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
